variables:
  DOCKER_CONFIG: "$CI_PROJECT_DIR/.docker"

stages:
  - validate
  # - plan
  - build
  - apply
  - provision
  - destroy

build-docker-image:
  stage: build
  image: docker:24.0.5
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "" # Vide pour l'instant pour établie la connection entre les conteneurs
  before_script:
    - mkdir -p $DOCKER_CONFIG  # Ensure the Docker config directory exists
    - echo "$PULL_PAT_TEST" | docker login -u "$CI_REGISTRY_USER" $CI_REGISTRY --password-stdin # Connection au registry gitlab
  script:
    - echo "Yé boiiiiii"
    # - docker build -t $CI_REGISTRY/ara1504621/terraform-test/app_temoin:v0.1 ./app
    # - docker push $CI_REGISTRY/ara1504621/terraform-test/app_temoin:v0.1
  artifacts:
    paths:
      - .docker/config.json
  tags:
    - build_job_docker
  # when: manual

validate:
  stage: validate
  image:
    name: hashicorp/terraform:latest
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  before_script:
    # - export AWS_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
    # - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - rm -rf .terraform
    - terraform --version
    - terraform init
  script:
    - terraform fmt -recursive
    - terraform validate
  artifacts:
    paths:
      - aws.cfg
  when: manual
        # on_success

# plan:
#   stage: plan
#   image:
#     name: hashicorp/terraform:latest
#     entrypoint:
#       - '/usr/bin/env'
#       - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
#   before_script:
#     - export AWS_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
#     - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
#     - rm -rf .terraform
#     - terraform --version
#     - terraform init
#   script:
#     - terraform plan
#   dependencies:
#     - validate

apply:
  stage: apply
  image:
    name: hashicorp/terraform:latest
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  before_script:
    # - export AWS_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
    # - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - rm -rf .terraform
    - terraform --version
    - terraform init
  script:
    - terraform apply --auto-approve
  dependencies:
    # - plan
    - validate
  when: manual

provision:
  stage: provision
  # image: python:3.9.17-slim-bullseye
  before_script:
    - export AWS_PROFILE=aws_profile
    # - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    # - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - export AWS_REGION='eu-west-3'
    # - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    # - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - export ANSIBLE_CONFIG=ansible.cfg
    # - ssh-agent bash && ssh-add /home/gitlab-runner/.ssh/Pjpro_key
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "/home/gitlab-runner/.ssh/Pjpro_key"
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    # - echo "$SSH_PRIVATE_KEY"
    # - mkdir -p ~/.ssh
    # - chmod 700 ~/.ssh
    - export ANSIBLE_PRIVATE_KEY_FILE=~/.ssh/Pjpro_key
  script:
    # - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    # - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - pwd
    # - pkill ssh-agent # Kill any running ssh-agent process running
    # - ssh-agent bash && ssh-add /home/gitlab-runner/.ssh/Pjpro_key
    # - sudo apt-get update && apt-get install ansible -y
    # - sudo apt-get install python3-boto3 awscli -y
    # - wget https://raw.githubusercontent.com/vshn/ansible-dynamic-inventory-ec2/master/ec2.py
    # - wget https://raw.githubusercontent.com/vshn/ansible-dynamic-inventory-ec2/master/ec2.ini
    # - sed -i 's/^regions =.*/regions = eu-west-3/' ec2.ini
    # - sed -i 's/^regions_exclude =.*/regions_exclude = us-gov-west-1,cn-north-1/' ec2.ini
    # # Alternatively, you can use a variable for the custom value
    # # - sed -i "s/^regions =.*/regions = $YOUR_CUSTOM_VALUE/" ec2.ini
    # - cat ec2.ini  # For debugging, to verify the changes
    # - export AWS_ACCESS_KEY_ID='AKIAYM4CN735ZH4AQ5DO'
    # - export AWS_SECRET_ACCESS_KEY='Q2BjLHWauvhcTkQoBN62RqQnOuSq4IEhu0IaInQd'
    # - aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID" --profile my_profile
    # - aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY" --profile my_profile
    # - aws configure set region eu-west-3 --profile my_profile
    - cat ~/.aws/credentials
    - cat ~/.aws/config
    - aws sts get-caller-identity
    - ansible --version
    - ansible -m ping all
    - ansible-inventory --list
    - ansible-inventory --graph
    - ansible-playbook -i inventory.aws_ec2.yaml playbook.yml
  when: manual
  needs:
    - apply

deploy_app:
  stage: provision
  # image: python:3.9.17-slim-bullseye
  before_script:
    - export AWS_PROFILE=aws_profile
    - export AWS_REGION='eu-west-3'
    - export ANSIBLE_CONFIG=ansible.cfg
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "/home/gitlab-runner/.ssh/Pjpro_key"
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - export ANSIBLE_PRIVATE_KEY_FILE=~/.ssh/Pjpro_key
  script:
    - pwd
    - cat ~/.aws/credentials
    - cat ~/.aws/config
    - aws sts get-caller-identity
    - cp .docker/config.json $CI_PROJECT_DIR
    - ansible --version
    - ansible -m ping all
    - ansible-inventory --list
    - ansible-inventory --graph
    - ansible-playbook -i inventory.aws_ec2.yaml playbook_2.yml
  when: manual
  needs:
    # - provision
    - job: build-docker-image
      artifacts: true


destroy:
  stage: destroy
  before_script:
    - rm -rf .terraform
    - terraform --version
    - terraform init
  script:
    - terraform destroy --auto-approve
  dependencies:
    - apply
  when: manual