- hosts: tag_role_Master
  become: true
  tasks:
    - name: Debug Execution Environment
      debug:
        msg: "Working directory: {{ ansible_env.PWD }}"
    - name: Check current user
      shell: whoami
      register: current_user
    - debug:
      var: current_user.stdout

    - name: Find config.json file
      shell: find / -name "config.json" 2>/dev/null
      register: config_json_files

    - debug:
      var: config_json_files.stdout_lines

    - name: Include subdirectory playbook
      include_tasks: playbooks/registry_secret.yml
      vars:
        key_path: "/config.json"

# - import_playbook: ./playbooks/registry_secret.yml
- import_playbook: ./playbooks/app.yml