- hosts: tag_role_Master
  become: true
  tasks:
    - name: Copy config.json to remote system
      copy:
        src: "{{ playbook_dir }}/.docker/config.json"
        dest: /home/ubuntu/config.json
        mode: '0644'

    - name: Include subdirectory playbook
      include_tasks: playbooks/registry_secret.yml
      vars:
        key_path: "/home/ubuntu/config.json"

# - import_playbook: ./playbooks/registry_secret.yml
- hosts: tag_role_Master
  become: true
  tasks:
    - name: Include subdirectory playbook
      include_tasks: playbooks/app.yml