- hosts: tag_role_Master
  become: true
  tasks:
    - name: Debug Execution Environment
      debug:
        msg: "Working directory: {{ ansible_env.PWD }}"
    - name: Include subdirectory playbook
      include_tasks: playbooks/registry_secret.yml
      vars:
        key_path: "{{ playbook_dir }}/./.docker/config.json"

# - import_playbook: ./playbooks/registry_secret.yml
- import_playbook: ./playbooks/app.yml