- hosts: tag_role_Master
  become: true
  tasks:
    - name: Create deployment pulling private image
      kubernetes.core.k8s:
        state: present
        kubeconfig: /home/ubuntu/.kube/config
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: app-container
            namespace: default
          spec:
            replicas: 4
            selector:
              matchLabels:
                app: demo-app
            template:
              metadata:
                labels:
                  app: demo-app
              spec:
                containers:
                  - name: dum-app-container
                    image: registry.gitlab.com/ara1504621/terraform-test/graph_stock_pyapp_devenv1.0:rcandidate
                    ports:
                      - containerPort: 5000
                imagePullSecrets:
                  - name: gitlab-cred

    - name: Expose deployment using nodePort
      kubernetes.core.k8s:
        state: present
        kubeconfig: /home/ubuntu/.kube/config
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: app-nodeport-service
            namespace: default
          spec:
            type: NodePort
            selector:
              app: demo-app
            ports:
              - protocol: TCP
                port: 5000
                targetPort: 5000
