- name: Restart Deployments
  hosts: tag_role_Master  # or your control plane node(s)
  become: yes
  tasks:
    
    - name: Wait for resources to start
      command: sleep 30

    - name: Check pods, svc, deployments
      command: kubectl get all -n default --kubeconfig /etc/kubernetes/admin.conf
      register: kubectl_all_result
    
    - name: Check secret
      command: kubectl get secret --kubeconfig /etc/kubernetes/admin.conf
      register: kubectl_secret_result

    - name: Check ConfigMap
      command: kubectl get configmap --kubeconfig /etc/kubernetes/admin.conf
      register: kubectl_configmap_result

    - name: Display resources deployed in K8s
      debug:
        msg: "{{ kubectl_all_result.stdout }}"
    
    - name: Display secret created in K8s
      debug:
        msg: "{{ kubectl_secret_result.stdout }}"

    - name: Display configmap created in K8s
      debug:
        msg: "{{ kubectl_configmap_resultstdout }}"