- name: Restart Deployments
  hosts: tag_role_Master  # or your control plane node(s)
  become: yes
  tasks:
    
    - name: Wait for resources to start
      command: sleep 30

    - name: Check deployments
      command: kubectl get deployments -n default --kubeconfig /etc/kubernetes/admin.conf
      register: kubectl_deployments_result
    
    - name: Check secret
      command: kubectl get secret -o name --kubeconfig /etc/kubernetes/admin.conf
      register: kubectl_secret_result

    - name: Check ConfigMap
      command: kubectl get configmap -o name --kubeconfig /etc/kubernetes/admin.conf
      register: kubectl_configmap_result
    
    - name: Check app service
      command: kubectl get svc app-nodeport-service --kubeconfig /etc/kubernetes/admin.conf
      register: kubectl_svc_result

    - name: Display deployments deployed in K8s
      debug:
        msg: "{{ kubectl_deployments_result.stdout }}"
    
    - name: Display secret created in K8s
      debug:
        msg: "{{ kubectl_secret_result.stdout }}"

    - name: Display configmap created in K8s
      debug:
        msg: "{{ kubectl_configmap_result.stdout }}"
    
    - name: Display app service created in K8s
      debug:
        msg: "{{ kubectl_svc_result.stdout }}"