- hosts: tag_role_Master
  become: true
  tasks:
    - name: Create configmap for mysql db
      kubernetes.core.k8s:
        state: present
        kubeconfig: /home/ubuntu/.kube/config
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: hydrate-script
            namespace: default
          data:
            hydrate.sql: |
              CREATE DATABASE devdb;
              USE devdb;
              CREATE TABLE IF NOT EXISTS stock_data (Date DATE, Open FLOAT, High FLOAT, Low FLOAT, Close FLOAT, AdjClose FLOAT, Volume INT, StockName VARCHAR(10), PRIMARY KEY (Date, StockName));
              CREATE USER 'workshop_reader'@'%' IDENTIFIED BY '@Cdevops_69100'; GRANT SELECT ON stock_data TO 'workshop_reader'@'%';FLUSH PRIVILEGES;
              
              -- Coherent sample data for MSFT
              INSERT INTO stock_data (Date, Open, High, Low, Close, AdjClose, Volume, StockName) 
              VALUES 
                ('2023-01-01', 120.00, 125.00, 119.00, 123.00, 123.00, 1000000, 'MSFT'),
                ('2023-01-02', 123.00, 128.00, 122.00, 126.00, 126.00, 1100000, 'MSFT'),
                ('2023-01-03', 126.00, 130.00, 125.00, 127.00, 127.00, 1200000, 'MSFT'),
                ('2023-01-04', 127.00, 129.00, 124.00, 125.00, 125.00, 1300000, 'MSFT'),
                ('2023-01-05', 125.00, 127.00, 123.00, 124.00, 124.00, 1400000, 'MSFT'),
                ('2023-01-06', 124.00, 126.00, 121.00, 123.00, 123.00, 1500000, 'MSFT'),
                ('2023-01-07', 123.00, 128.00, 120.00, 122.00, 122.00, 1600000, 'MSFT'),
                ('2023-01-08', 122.00, 125.00, 121.00, 124.00, 124.00, 1700000, 'MSFT'),
                ('2023-01-09', 124.00, 127.00, 123.00, 126.00, 126.00, 1800000, 'MSFT'),
                ('2023-01-10', 126.00, 130.00, 125.00, 128.00, 128.00, 1900000, 'MSFT'),
                ('2023-01-11', 128.00, 133.00, 127.00, 130.00, 130.00, 2000000, 'MSFT'),
                ('2023-01-12', 130.00, 135.00, 129.00, 132.00, 132.00, 2100000, 'MSFT');
              
              -- Coherent sample data for AMZN
              INSERT INTO stock_data (Date, Open, High, Low, Close, AdjClose, Volume, StockName) 
              VALUES 
                ('2023-01-01', 3000.00, 3050.00, 2980.00, 3025.00, 3025.00, 2000000, 'AMZN'),
                ('2023-01-02', 3025.00, 3070.00, 3010.00, 3045.00, 3045.00, 2100000, 'AMZN'),
                ('2023-01-03', 3045.00, 3090.00, 3030.00, 3060.00, 3060.00, 2200000, 'AMZN'),
                ('2023-01-04', 3060.00, 3100.00, 3040.00, 3080.00, 3080.00, 2300000, 'AMZN'),
                ('2023-01-05', 3080.00, 3120.00, 3060.00, 3100.00, 3100.00, 2400000, 'AMZN'),
                ('2023-01-06', 3100.00, 3150.00, 3090.00, 3125.00, 3125.00, 2500000, 'AMZN'),
                ('2023-01-07', 3125.00, 3170.00, 3110.00, 3150.00, 3150.00, 2600000, 'AMZN'),
                ('2023-01-08', 3150.00, 3200.00, 3130.00, 3180.00, 3180.00, 2700000, 'AMZN'),
                ('2023-01-09', 3180.00, 3230.00, 3160.00, 3210.00, 3210.00, 2800000, 'AMZN'),
                ('2023-01-10', 3210.00, 3260.00, 3190.00, 3240.00, 3240.00, 2900000, 'AMZN'),
                ('2023-01-11', 3240.00, 3300.00, 3220.00, 3270.00, 3270.00, 3000000, 'AMZN'),
                ('2023-01-12', 3270.00, 3330.00, 3250.00, 3300.00, 3300.00, 3100000, 'AMZN');
    
    - name: Hydrate the db
      kubernetes.core.k8s:
        state: present
        kubeconfig: /home/ubuntu/.kube/config
        definition:
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: hydrate-mysql
            namespace: default
          spec:
            template:
              spec:
                containers:
                - name: mysql
                  image: mysql:5.7
                  command: ["sh", "-c", "mysql -h mysql -uroot -pDevtest01 < /data/hydrate.sql"]
                  volumeMounts:
                  - name: hydrate-script
                    mountPath: /data
                restartPolicy: OnFailure
                volumes:
                - name: hydrate-script
                  configMap:
                    name: hydrate-script
      
