- hosts: tag_role_Master
  become: true
  tasks:
    - name: Create mysql deployment
      kubernetes.core.k8s:
        state: present
        kubeconfig: /home/ubuntu/.kube/config
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: mysql
            namespace: default
          spec:
            selector:
              matchLabels:
                app: mysql
            strategy:
              type: Recreate
            template:
              metadata:
                labels:
                  app: mysql
              spec:
                containers:
                - image: mysql:5.7
                  name: mysql
                  env:
                  - name: MYSQL_ROOT_PASSWORD
                    value: "Devtest01"
                  ports:
                  - containerPort: 3306
                    name: mysql
                   

    - name: Privately expose mysql deployment
      kubernetes.core.k8s:
        state: present
        kubeconfig: /home/ubuntu/.kube/config
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: mysql
            namespace: default
          spec:
            type: ClusterIP
            ports:
            - protocol: TCP
              port: 3306
              targetPort: 3306
            selector:
              app: mysql
    
    - name: Rollout restart CoreDNS deployment in kube-system namespace
      command: kubectl -n kube-system rollout restart deployment coredns --kubeconfig /etc/kubernetes/admin.conf
      register: rollout_result
      failed_when: "'error' in rollout_result.stderr.lower() or rollout_result.rc != 0"
      changed_when: "'deployment.apps/coredns restarted' in rollout_result.stdout"
    
    - name: Wait for coredns to restart
      command: sleep 20
    
    - name: Create ephemeral container to test the connection to the database
      kubernetes.core.k8s:
        state: present
        kubeconfig: /home/ubuntu/.kube/config
        definition:
          apiVersion: v1
          kind: Pod
          metadata:
            name: mysql-client
            namespace: default
          spec:
            containers:
            - name: mysql-client
              image: mysql:5.7
              command: ["sh", "-c", "until mysql -h mysql -uroot -pDevtest01 -e 'show databases'; do echo waiting for mysql; sleep 5; done"]
            restartPolicy: OnFailure
