---
- hosts: tag_role_Master
  become: true
  tasks:
    - name: get join command
      command: /usr/bin/kubeadm token create --print-join-command
      register: join_command_raw
    - debug: msg="{{ join_command_raw.stdout_lines[0] }}"

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"


- hosts: tag_role_Worker
  become: true
  tasks:
    - name: remove swap
      command: /sbin/swapoff -a

    - name: fetch join command from master
      set_fact:
        join_command: "{{ hostvars[groups['tag_role_Master'][0]].join_command }}"

    - name: join cluster
      command: "{{ join_command }}"
      environment:
        HOME: /home/ubuntu/

- name: Apply calico CNI
  hosts: tag_role_Master
  become: yes
  tasks: 
    - name: Apply Calico manifest
      command: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml
      environment:
        HOME: /home/ubuntu/
