  
- name: Create deployment pulling private image
  kubernetes.core.k8s:
    state: present
    kubeconfig: /home/ubuntu/.kube/config
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: app-container
        namespace: default
      spec:
        replicas: 4
        selector:
          matchLabels:
            app: demo-app
        template:
          metadata:
            labels:
              app: demo-app
          spec:
            containers:
              - name: dum-app-container
                image: registry.gitlab.com/ara1504621/terraform-test/app_temoin:v0.1
                ports:
                  - containerPort: 80
            imagePullSecrets: 
              - name: gitlab-cred

- name : Expose the deployment
  become_user: ubuntu
  shell : kubectl expose deployment/app-container --type="LoadBalancer" --port=80 --target-port=80

- name: Get the service exposed port
  become_user: ubuntu
  shell: kubectl get services/app-container
  register: load_balancer_output

- name: display NodePort exposed port value 
  debug:
    var: load_balancer_output.stdout