---
- name: Gather EC2 instances information
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Gather EC2 instances info
      amazon.aws.ec2_instance_info:
        filters:
          - tag:role: "Master"
          - tag:role: "Worker" # Adjust this filter based on your tagging
      register: ec2_info

- name: Set host facts for each EC2 instance
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Set facts for EC2 instances
      set_fact:
        ec2_instances: "{{ ec2_info.instances }}"
    
    - name: Print debug information
      debug:
        msg: "{{ ec2_instances }}"

- name: Update /etc/hosts on all EC2 instances
  hosts: all
  tasks:
    - name: Ensure /etc/hosts has entries for all EC2 instances
      blockinfile:
        path: /etc/hosts
        block: |
          {% for instance in hostvars['localhost']['ec2_instances'] %}
          {{ instance.private_ip_address }} {{ instance.tags.Name }}
          {% endfor %}

