- hosts: tag_role_Master
  become: true
  tasks:
    - name: Create configmap for mysql db
      kubernetes.core.k8s:
        state: present
        kubeconfig: /home/ubuntu/.kube/config
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: hydrate-script
            namespace: default
          data:
            hydrate.sql: |
              CREATE DATABASE devdb;
              USE devdb;
              CREATE TABLE IF NOT EXISTS stock_data (Date DATE, Open FLOAT, High FLOAT, Low FLOAT, Close FLOAT, AdjClose FLOAT, Volume INT, StockName VARCHAR(10), PRIMARY KEY (Date, StockName));
              CREATE USER 'workshop_reader'@'%' IDENTIFIED BY '@Cdevops_69100'; GRANT SELECT ON stock_data TO 'workshop_reader'@'%';FLUSH PRIVILEGES;
              
              -- Coherent sample data for MSFT
              INSERT INTO stock_data (Date, Open, High, Low, Close, AdjClose, Volume, StockName) 
              VALUES 
                ('2022-01-04', 124.00, 126.50, 122.50, 125.50, 124.00, 56289012, 'MSFT'),
                ('2022-01-05', 125.50, 128.00, 123.00, 127.00, 126.00, 57890012, 'MSFT'),
                ('2022-01-06', 127.00, 129.50, 125.50, 128.50, 127.00, 58901234, 'MSFT'),
                ('2022-01-07', 128.50, 130.00, 126.50, 129.50, 128.00, 59234567, 'MSFT'),
                ('2022-01-08', 129.50, 131.00, 127.50, 130.50, 129.00, 60345678, 'MSFT');
              
              -- Coherent sample data for AMZN
              INSERT INTO stock_data (Date, Open, High, Low, Close, AdjClose, Volume, StockName) 
              VALUES 
                ('2022-01-04', 350.00, 355.00, 345.00, 352.00, 351.00, 12456789, 'AMZN'),
                ('2022-01-05', 352.00, 358.00, 348.00, 354.00, 353.00, 12567890, 'AMZN'),
                ('2022-01-06', 354.00, 360.00, 350.00, 356.00, 355.00, 12678901, 'AMZN'),
                ('2022-01-07', 356.00, 362.00, 352.00, 358.00, 357.00, 12789012, 'AMZN'),
                ('2022-01-08', 358.00, 364.00, 354.00, 360.00, 359.00, 12890123, 'AMZN');
    
    - name: Hydrate the db
      kubernetes.core.k8s:
        state: present
        kubeconfig: /home/ubuntu/.kube/config
        definition:
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: hydrate-mysql
            namespace: default
          spec:
            template:
              spec:
                containers:
                - name: mysql
                  image: mysql:5.7
                  command: ["sh", "-c", "mysql -h mysql -uroot -pDevtest01 < /data/hydrate.sql"]
                  volumeMounts:
                  - name: hydrate-script
                    mountPath: /data
                restartPolicy: OnFailure
                volumes:
                - name: hydrate-script
                  configMap:
                    name: hydrate-script
      
