- hosts: tag_role_Master
  become: true
  tasks:
    - name: Create k8sgpt crd
      kubernetes.core.k8s:
        state: present
        kubeconfig: /home/ubuntu/.kube/config
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: hydrate-script
            namespace: default
          data:
            hydrate.sql: |
              CREATE DATABASE devdb;
              USE devdb;
              CREATE TABLE IF NOT EXISTS stock_data (Date DATE, Open FLOAT, High FLOAT, Low FLOAT, Close FLOAT, AdjClose FLOAT, Volume INT, StockName VARCHAR(10), PRIMARY KEY (Date, StockName));
              CREATE USER 'workshop_reader'@'%' IDENTIFIED BY '@Cdevops_69100'; GRANT SELECT ON ${aws_db_instance.default.db_name}.* TO 'workshop_reader'@'%';FLUSH PRIVILEGES;
              INSERT INTO stock_data (Date, Open, High, Low, Close, AdjClose, Volume, StockName) VALUES ('2022-01-03', 177.830002, 182.880005, 177.710007, 182.009995, 179.953888, 104487900, 'AAPL');
              INSERT INTO stock_data (Date, Open, High, Low, Close, AdjClose, Volume, StockName) VALUES ('2022-01-03', 123.45, 125.67, 121.34, 124.56, 123.12, 56789012, 'MSFT');
              INSERT INTO stock_data (Date, Open, High, Low, Close, AdjClose, Volume, StockName) VALUES ('2022-01-03', 345.67, 356.78, 341.23, 350.11, 348.90, 12345678, 'AMZN');
    
    - name: Create k8sgpt crd
      kubernetes.core.k8s:
        state: present
        kubeconfig: /home/ubuntu/.kube/config
        definition:
        apiVersion: batch/v1
        kind: Job
        metadata:
          name: hydrate-mysql
          namespace: default
        spec:
          template:
            spec:
              containers:
              - name: mysql
                image: mysql:5.7
                command: ["sh", "-c", "mysql -h mysql -uroot -pDevtest01 < /data/hydrate.sql"]
                volumeMounts:
                - name: hydrate-script
                  mountPath: /data
              restartPolicy: OnFailure
              volumes:
              - name: hydrate-script
                configMap:
                  name: hydrate-script
      
