- name: Read the secret from build job artifact .json
  slurp:
    src: "{{ key_path }}"
  register: gitlab_config

# - name: create an empty file for gitlab registry secret manifest
#   copy:
#     content: ""
#     dest: /home/ubuntu/gitlab_secret.yml
#     force: false

- name: Create Kubernetes secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: gitlab_cred
        namespace: default
      data:
        .dockerconfigjson: "{{ gitlab_config.content | b64encode }}"
      type: kubernetes.io/dockerconfigjson