- hosts: tag_role_Master
  become: yes
  vars: 
    - key_path:
  tasks:
    - name: Copy the secret from build job artifact
      copy:
        src: "{{ key_path }}"
        dest: 
    - name: create an empty file for gitlab registry secret manifest
      copy:
        content: ""
        dest: /home/ubuntu/gitlab_secret.yml
        force: no

    - name: configuring the manifest for 2048 deployment
      blockinfile:
        path: /home/ubuntu/gitlab_secret.yml
        block: |
             apiVersion: v1
             kind: Secret
             metadata:
               name: gitlab_access_key
               namespace: dum_app
             data:
               .dockerconfigjson: 
             type: kubernetes.io/dockerconfigjson