- hosts: tag_role_Master
  become: true
  tasks:
    - name: Copy config.json to remote system
      copy:
        src: "{{ playbook_dir }}/.docker/config.json"
        dest: /home/ubuntu/config.json
        mode: '0644'

    - name: Include subdirectory playbook
      include_tasks: playbooks/registry_secret.yml
      vars:
        key_path: "/home/ubuntu/config.json"
    
    - name: Read the secret from build job artifact .json
      slurp:
        src: "{{ key_path }}"
      register: gitlab_config

# - name: create an empty file for gitlab registry secret manifest
#   copy:
#     content: ""
#     dest: /home/ubuntu/gitlab_secret.yml
#     force: false

    - name: Create Kubernetes secret
      kubernetes.core.k8s:
        state: present
        kubeconfig: /home/ubuntu/.kube/config
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: gitlab-cred
            namespace: default
          data:
            .dockerconfigjson: "{{ gitlab_config.content | b64decode | b64encode }}"
          type: kubernetes.io/dockerconfigjson