- name: Debug Execution Environment
  debug:
    msg: "Working directory: {{ ansible_env.PWD }}"
- name: Check current user
  shell: whoami
  register: current_user
- debug:
    var: current_user.stdout

- name: Find config.json file
  shell: find / -name "config.json" 2>/dev/null
  register: config_json_files

- debug:
    var: config_json_files.stdout_lines

- name: Read the secret from build job artifact .json
  slurp:
    src: "{{ key_path }}"
  register: gitlab_config

# - name: create an empty file for gitlab registry secret manifest
#   copy:
#     content: ""
#     dest: /home/ubuntu/gitlab_secret.yml
#     force: false

- name: Create Kubernetes secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: gitlab_cred
        namespace: default
      data:
        .dockerconfigjson: "{{ gitlab_config.content | b64encode }}"
      type: kubernetes.io/dockerconfigjson